

main_cate = '''
        <map name="topMultiLinkMap-2">

            <area shape="rect" coords="193,164,336,332" href="/np/campaigns/11727" alt="패션.잡화" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
            <area shape="rect" coords="336,163,470,331" href="/np/campaigns/12456" alt="뷰티" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
            <area shape="rect" coords="471,163,605,331" href="https://www.coupang.com/np/campaigns/11725/components/221834" alt="출산.유아동" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
            <area shape="rect" coords="606,164,740,332" href="https://www.coupang.com/np/campaigns/11725/components/194176" alt="식품" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
            <area shape="rect" coords="747,164,881,332" href="https://www.coupang.com/np/campaigns/11725/components/185569" alt="주방용품" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
            <area shape="rect" coords="193,344,336,512" href="https://www.coupang.com/np/campaigns/11725/components/115573" alt="생활용품" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
            <area shape="rect" coords="336,344,469,512" href="https://www.coupang.com/np/campaigns/11725/components/184455" alt="홈인테리어" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
            <area shape="rect" coords="470,346,603,514" href="https://www.coupang.com/np/campaigns/11725/components/178155" alt="가전.디지털" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
            <area shape="rect" coords="605,346,738,514" href="https://www.coupang.com/np/campaigns/11725/components/317678" alt="스포츠.레저" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
            <area shape="rect" coords="745,348,878,516" href="https://www.coupang.com/np/campaigns/11725/components/183960" alt="자동차용품" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
            <area shape="rect" coords="201,532,334,700" href="https://www.coupang.com/np/campaigns/11725/components/317679" alt="완구.취미" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
            <area shape="rect" coords="336,532,469,700" href="https://www.coupang.com/np/campaigns/11725/components/177195" alt="문구.오피스" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
            <area shape="rect" coords="474,531,607,699" href="https://www.coupang.com/np/campaigns/11725/components/115574" alt="반려동물" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
            <area shape="rect" coords="610,532,743,700" href="https://www.coupang.com/np/campaigns/15905" alt="헬스.건강식품" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
            <area shape="rect" coords="746,532,879,700" href="https://pages.coupang.com/p/78273" alt="여행.티켓" data-web-log-event="click" data-web-log-param="{ &quot;campaignId&quot;: &quot;83&quot;, &quot;data&quot;: { &quot;domain&quot;: &quot;plp&quot;, &quot;logCategory&quot;: &quot;event&quot;, &quot;logType&quot;: &quot;click&quot;, &quot;pageName&quot;: &quot;plp&quot;, &quot;eventName&quot;: &quot;click_multi_link_banner&quot;, &quot;imageId&quot;: &quot;1082722&quot;, &quot;trCid&quot;: &quot;705547&quot;, &quot;trAid&quot;: &quot;campaign_plp_wide&quot;, &quot;bannerId&quot;: &quot;705547&quot; }, &quot;meta&quot;: { &quot;schemaId&quot;: 2544, &quot;schemaVersion&quot;: 1 } }">
            
        </map>
    </div>
'''